In [27]:
import pandas as pd 
import numpy as np 
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
data = pd.read_csv("/var/www/Receipt-Intelligence/data/synthetic.csv")
data.head()

,text,category
0,OANDO petrol,transport
1,MEDPLUS prescription bandage,health
2,NETFLIX amusement park ticket concert ticket v...,entertainment
3,ALPHA PHARMACY face mask hand sanitizer,health
4,CVS PHARMACY antibiotics first aid,health


In [29]:
train, test = train_test_split(data, test_size=0.2, random_state=42, stratify=data['category'])

In [30]:
X_train = train['text']
y_train = train['category']
X_test = test['text']   
y_test = test['category']

In [31]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df = 1)

train_matrix = vectorizer.fit_transform(X_train)
test_matrix = vectorizer.transform(X_test)

In [32]:
model = MultinomialNB()
model.fit(train_matrix, y_train)
model.score(test_matrix, y_test)

0.9921875

In [ ]:
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer(ngram_range=(1, 2), min_df = 1)),
    ('classifier', LogisticRegression(random_state=42))
])
pipeline.fit(X_train, y_train)

In [35]:
predictions = pipeline.predict(X_test)

print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

               precision    recall  f1-score   support

       dining       1.00      1.00      1.00        16
entertainment       1.00      1.00      1.00        16
    groceries       0.89      1.00      0.94        16
       health       1.00      1.00      1.00        16
        other       1.00      1.00      1.00        16
     shopping       1.00      0.94      0.97        16
    transport       1.00      1.00      1.00        16
    utilities       1.00      0.94      0.97        16

     accuracy                           0.98       128
    macro avg       0.99      0.98      0.98       128
 weighted avg       0.99      0.98      0.98       128

[[16  0  0  0  0  0  0  0]
 [ 0 16  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0]
 [ 0  0  0  0 16  0  0  0]
 [ 0  0  1  0  0 15  0  0]
 [ 0  0  0  0  0  0 16  0]
 [ 0  0  1  0  0  0  0 15]]
